"""``run_metadata.json``: what produced a run, and what reads it back (P14).

Until this landed, attribution rested entirely on the results-directory name --
``scripts/compare_models.py`` carried a comment saying exactly that. The cost was
not theoretical: the P29 attribution experiment has to harvest into a
config-named root after *each* batch, because both batches emit identically-named
``Prediction_Output_<Model>_<stamp>`` directories into one working directory, and
sorting them afterwards would mean inferring the config from timestamp order
alone -- in the one experiment whose entire purpose is attribution.

Three properties are load-bearing here and each has its own section below.

**The record is self-sufficient.** ``pipeline`` carries the registry *name* and
all three fields. A name with no reader was the P4 lesson; a name with no fields
is its sibling. If the registry is ever edited, the fields still say what ran.

**The fold split is identified by content, not by name.**
``data/folds_grouped/`` is gitignored and regenerated by
``scripts/make_folds.py``, so the git SHA cannot cover it -- git never saw those
files. ``fold_dir: folds_grouped`` alone therefore does not identify a split, and
without the hash a corrected or DRG run is not reproducible from its own record.

**Writing it can never cost a run.** A 13-minute baseline run or a 35-minute
three-model run whose numbers are already on disk must not be lost to a git
lookup. Every failure path is asserted to warn and return rather than raise.

The synthetic fold directories are built under a tmp *repo root* rather than
pointed at ``data/``: ``folds_grouped/`` is regenerated output that may legally
be absent, so a test reading it would pass or fail on whether somebody had run
``make_folds.py`` -- which is not what any of these tests are about.
"""

from __future__ import annotations

import json
import os
import subprocess

import pytest

from aicds import runs
from aicds.config import (
    GRADER_DRG,
    LEGACY,
    PIPELINE_NAMES,
    PipelineConfig,
    from_name,
    name_of,
)
from aicds.utils.Constants import K_FOLD

import scripts.compare_models as compare_models


# ---------------------------------------------------------------------------
# Fixtures: a synthetic repo root with two different fold splits
# ---------------------------------------------------------------------------


def _write_fold_dir(repo_root, fold_dir, payload):
    """A minimal ``<repo_root>/data/<fold_dir>/Fold{0,1}/`` split."""
    for fold in (0, 1):
        directory = os.path.join(repo_root, "data", fold_dir, "Fold%d" % fold)
        os.makedirs(directory, exist_ok=True)
        for name in ("TrainingSet.txt", "TestSet.txt"):
            with open(os.path.join(directory, name), "w", encoding="utf-8") as handle:
                handle.write("%s/%s/%d\n" % (payload, name, fold))
    return os.path.join(repo_root, "data", fold_dir)


@pytest.fixture
def repo(tmp_path):
    """A tmp repo root carrying ``folds`` and ``folds_grouped`` with distinct content."""
    root = str(tmp_path / "repo")
    _write_fold_dir(root, "folds", "legacy-split")
    _write_fold_dir(root, "folds_grouped", "grouped-split")
    return root


@pytest.fixture
def run_dir(tmp_path):
    path = str(tmp_path / "run")
    os.makedirs(path)
    return path


def _write_and_read(run_dir, config, model_name, stamp, repo_root):
    path = runs.write_run_metadata(
        run_dir, config, model_name, stamp, repo_root=repo_root
    )
    assert path is not None, "write_run_metadata returned None on a healthy path"
    with open(path, encoding="utf-8") as handle:
        return json.load(handle), path


# ---------------------------------------------------------------------------
# The payload: every field, for both a legacy and a DRG run
# ---------------------------------------------------------------------------


class TestPayload:
    def test_legacy_run_records_every_field(self, run_dir, repo):
        payload, path = _write_and_read(
            run_dir, LEGACY, "BioSentVec", "05082026_18-55-32", repo
        )

        assert os.path.basename(path) == "run_metadata.json"
        assert payload["metadata_version"] == 1
        assert payload["stamp"] == "05082026_18-55-32"
        assert payload["k_fold"] == K_FOLD

        assert payload["pipeline"] == {
            "name": "legacy",
            "fold_dir": "folds",
            "preprocess_version": "legacy",
            "grader": "cosine",
        }
        assert payload["model"] == {"key": "baseline", "label": "BioSentVec"}

        # The hash exists and is a hex sha256; its *stability* is tested below.
        assert isinstance(payload["fold_dir_sha256"], str)
        assert len(payload["fold_dir_sha256"]) == 64
        # The split hashed, so nothing is missing. (``git_unavailable`` is
        # expected here and only here: the fixture repo root is a tmp directory
        # with no working tree, which is precisely the "don't know" branch.)
        assert "fold_dir_missing" not in payload["notes"]

        assert set(payload["git"]) == {"sha", "dirty"}
        assert set(payload["environment"]) == {"platform", "python", "numpy"}
        assert payload["environment"]["python"].count(".") >= 1

    def test_git_state_is_captured_against_a_real_working_tree(self, run_dir):
        """The fixture root has no ``.git``; this repository does.

        Run against ``REPO_ROOT`` -- which is how both arms call it, and NEVER
        ``os.getcwd()``: the golden chdirs into a tmp directory, so a cwd-based
        lookup would record the wrong repository or nothing at all.
        """
        payload, _ = _write_and_read(
            run_dir, LEGACY, "BioSentVec", "05082026_18-55-32", runs.REPO_ROOT
        )
        if payload["git"]["sha"] is None:  # no git on this machine
            pytest.skip("git unavailable")
        assert len(payload["git"]["sha"]) == 40
        assert set(payload["git"]["sha"]) <= set("0123456789abcdef")
        assert isinstance(payload["git"]["dirty"], bool)
        assert payload["notes"] == []

    def test_drg_run_records_the_grader_that_actually_ran(self, run_dir, repo):
        payload, _ = _write_and_read(
            run_dir, GRADER_DRG, "Bio_ClinicalBERT", "06082026_15-31-02", repo
        )
        assert payload["pipeline"] == {
            "name": "drg",
            "fold_dir": "folds_grouped",
            "preprocess_version": "corrected",
            "grader": "drg-exact",
        }
        assert payload["model"] == {
            "key": "bio_clinical_bert",
            "label": "Bio_ClinicalBERT",
        }

    def test_the_recorded_name_round_trips_through_the_registry(self, run_dir, repo):
        """``from_name(payload['pipeline']['name'])`` must rebuild the same config.

        This is the property that lets a reader trust the name instead of the
        three fields, and it is what ``compare_models.recorded_pipeline`` relies
        on.
        """
        payload, _ = _write_and_read(run_dir, GRADER_DRG, "BlueBERT", "0" * 8 + "_00-00-00", repo)
        assert from_name(payload["pipeline"]["name"]) == GRADER_DRG

    def test_json_is_sorted_indented_and_newline_terminated(self, run_dir, repo):
        path = runs.write_run_metadata(
            run_dir, LEGACY, "BiomedBERT", "05082026_19-38-16", repo_root=repo
        )
        with open(path, encoding="utf-8", newline="") as handle:
            text = handle.read()
        assert text.endswith("\n")
        # newline="\n" at write time, so the bytes match on Windows and Linux --
        # this file is a provenance record that gets compared across the two.
        assert "\r\n" not in text
        assert "\n  " in text, "expected indent=2"
        keys = [line.split('"')[1] for line in text.splitlines() if line.startswith("  \"")]
        assert keys == sorted(keys), keys

    def test_an_unregistered_model_name_warns_rather_than_writing_a_guess(
        self, run_dir, repo, capsys
    ):
        """``model_key`` refuses invented keys; the never-raises policy takes it from there."""
        assert runs.write_run_metadata(run_dir, LEGACY, "GPT-9", "0" * 8 + "_00-00-00", repo_root=repo) is None
        assert "[WARN] run_metadata.json not written" in capsys.readouterr().out
        assert not os.path.exists(os.path.join(run_dir, "run_metadata.json"))


# ---------------------------------------------------------------------------
# The fold-split hash
# ---------------------------------------------------------------------------


class TestFoldDigest:
    def test_stable_across_calls(self, repo):
        first = runs.fold_dir_digest("folds", repo_root=repo)
        second = runs.fold_dir_digest("folds", repo_root=repo)
        assert first == second
        assert first is not None

    def test_differs_between_fold_dirs(self, repo):
        assert runs.fold_dir_digest("folds", repo_root=repo) != runs.fold_dir_digest(
            "folds_grouped", repo_root=repo
        )

    def test_changes_when_a_fold_file_changes(self, repo):
        before = runs.fold_dir_digest("folds", repo_root=repo)
        target = os.path.join(repo, "data", "folds", "Fold1", "TestSet.txt")
        with open(target, "a", encoding="utf-8") as handle:
            handle.write("one more admission\n")
        assert runs.fold_dir_digest("folds", repo_root=repo) != before

    def test_changes_when_a_case_moves_between_folds(self, repo):
        """Which admission sits in which fold IS the split.

        A content-only hash would call these two experiments identical, because
        swapping two fold files leaves the multiset of bytes untouched. Hashing
        the relative path alongside the content is what prevents that.
        """
        before = runs.fold_dir_digest("folds", repo_root=repo)
        first = os.path.join(repo, "data", "folds", "Fold0", "TestSet.txt")
        second = os.path.join(repo, "data", "folds", "Fold1", "TestSet.txt")
        with open(first, encoding="utf-8") as handle:
            first_text = handle.read()
        with open(second, encoding="utf-8") as handle:
            second_text = handle.read()
        with open(first, "w", encoding="utf-8") as handle:
            handle.write(second_text)
        with open(second, "w", encoding="utf-8") as handle:
            handle.write(first_text)
        assert runs.fold_dir_digest("folds", repo_root=repo) != before

    def test_missing_fold_dir_is_null_and_noted(self, run_dir, repo):
        """Ordinary, not an error: folds_grouped/ is gitignored, regenerated output."""
        config = PipelineConfig(fold_dir="folds_that_were_never_generated")
        payload, _ = _write_and_read(
            run_dir, config, "BlueBERT", "05082026_19-52-30", repo
        )
        assert payload["fold_dir_sha256"] is None
        assert "fold_dir_missing" in payload["notes"]
        # The record is still complete about everything else.
        assert payload["pipeline"]["fold_dir"] == "folds_that_were_never_generated"


# ---------------------------------------------------------------------------
# The never-raises policy
# ---------------------------------------------------------------------------


class TestNeverRaises:
    def test_git_exploding_still_writes_the_run_record(
        self, run_dir, repo, monkeypatch, capsys
    ):
        """The numbers are already on disk. A git lookup may not take them down."""

        def explode(*args, **kwargs):
            raise RuntimeError("git went to lunch")

        monkeypatch.setattr(subprocess, "run", explode)

        payload, _ = _write_and_read(
            run_dir, LEGACY, "BioSentVec", "05082026_18-55-32", repo
        )
        assert payload["git"] == {"sha": None, "dirty": None}
        assert "git_unavailable" in payload["notes"]
        # And everything git had nothing to do with survived.
        assert payload["pipeline"]["name"] == "legacy"
        assert payload["fold_dir_sha256"] is not None

    def test_dirty_is_null_not_false_when_git_cannot_be_asked(
        self, run_dir, repo, monkeypatch
    ):
        """"clean" and "don't know" are different claims.

        The same distinction ``_git_ignores`` draws with its ``answered`` flag. A
        provenance record that asserts the first when it means the second is
        worse than one that admits the gap.
        """
        monkeypatch.setattr(
            subprocess, "run", lambda *a, **k: (_ for _ in ()).throw(OSError("no git"))
        )
        payload, _ = _write_and_read(run_dir, LEGACY, "BiomedBERT", "0" * 8 + "_00-00-00", repo)
        assert payload["git"]["dirty"] is None

    def test_unwritable_destination_warns_and_returns_none(self, repo, tmp_path, capsys):
        missing = str(tmp_path / "no" / "such" / "directory")
        assert runs.write_run_metadata(missing, LEGACY, "BlueBERT", "0" * 8 + "_00-00-00", repo_root=repo) is None
        assert "[WARN] run_metadata.json not written" in capsys.readouterr().out

    def test_a_fold_file_vanishing_mid_hash_warns_rather_than_raising(
        self, run_dir, repo, monkeypatch, capsys
    ):
        real_walk = os.walk

        def walk_then_delete(top, *args, **kwargs):
            result = list(real_walk(top, *args, **kwargs))
            for directory, _subdirs, files in result:
                for name in files:
                    os.remove(os.path.join(directory, name))
            return result

        monkeypatch.setattr(os, "walk", walk_then_delete)
        assert runs.write_run_metadata(run_dir, LEGACY, "BlueBERT", "0" * 8 + "_00-00-00", repo_root=repo) is None
        assert "[WARN] run_metadata.json not written" in capsys.readouterr().out


# ---------------------------------------------------------------------------
# name_of: the reverse lookup
# ---------------------------------------------------------------------------


class TestNameOf:
    def test_every_selectable_pipeline_round_trips(self):
        """The registry-completeness guard, extended to the reverse direction.

        ``test_drg_grader.test_every_selectable_pipeline_has_a_live_grader``
        makes the same shape of claim about graders: no config may be
        selectable-but-unhonoured. Here: no config may be selectable but
        unnameable, because a run driven by ``--pipeline X`` that records
        ``name: null`` would push every reader back onto the three fields and
        quietly undo half of P14.
        """
        for name in PIPELINE_NAMES:
            assert name_of(from_name(name)) == name

    def test_value_equality_not_identity(self):
        """A rebuilt config gets its name back. Frozen dataclass equality is the point."""
        rebuilt = PipelineConfig(
            fold_dir="folds_grouped",
            preprocess_version="corrected",
            grader="drg-exact",
        )
        assert rebuilt is not GRADER_DRG
        assert name_of(rebuilt) == "drg"

    def test_a_hand_built_config_is_none_not_an_error(self):
        """None is a first-class answer -- the three fields still identify the run."""
        hand_built = PipelineConfig(fold_dir="folds_grouped", grader="drg-exact")
        assert name_of(hand_built) is None

    def test_null_name_still_leaves_a_fully_described_pipeline(self, run_dir, repo):
        hand_built = PipelineConfig(fold_dir="folds_grouped", grader="drg-exact")
        payload, _ = _write_and_read(
            run_dir, hand_built, "BlueBERT", "0" * 8 + "_00-00-00", repo
        )
        assert payload["pipeline"] == {
            "name": None,
            "fold_dir": "folds_grouped",
            "preprocess_version": "legacy",
            "grader": "drg-exact",
        }


# ---------------------------------------------------------------------------
# The reader: compare_models.resolve_pipeline
# ---------------------------------------------------------------------------


def _make_run(root, key, stamp, pipeline_name=None):
    """A discoverable nested run, optionally carrying provenance."""
    path = os.path.join(root, key, stamp)
    os.makedirs(path, exist_ok=True)
    with open(os.path.join(path, "PerformanceIndex.txt"), "w", encoding="utf-8") as f:
        f.write("marker\n")
    if pipeline_name is not None:
        payload = {
            "metadata_version": 1,
            "pipeline": {
                "name": pipeline_name,
                "fold_dir": "folds",
                "preprocess_version": "legacy",
                "grader": "cosine",
            },
        }
        with open(os.path.join(path, "run_metadata.json"), "w", encoding="utf-8") as f:
            json.dump(payload, f)
    return path


class TestResolvePipeline:
    def test_metadata_beats_a_wrong_directory_name(self, tmp_path, capsys):
        """The whole point of P14: the tree says what it is, the folder only hints.

        The root is named ``results`` -- which ``_PIPELINE_BY_DIRNAME`` maps to
        ``legacy`` -- while the runs inside record ``drg``. Before this commit
        the folder name won and 16 sanity checks were run against the wrong
        pipeline's expectations.
        """
        root = str(tmp_path / "results")
        _make_run(root, "baseline", "06082026_15-18-52", "drg")
        _make_run(root, "biomedbert", "06082026_15-42-04", "drg")

        assert compare_models.resolve_pipeline(root, None) == "drg"
        out = capsys.readouterr().out
        assert "pipeline from run_metadata.json: drg" in out
        assert "inferring pipeline from directory name" not in out

    def test_a_metadata_less_tree_falls_back_and_says_so(self, tmp_path, capsys):
        root = str(tmp_path / "results_drg")
        _make_run(root, "baseline", "06082026_15-18-52")

        assert compare_models.resolve_pipeline(root, None) == "drg"
        out = capsys.readouterr().out
        assert "[WARN] no run_metadata.json under" in out
        assert "pre-C8 runs" in out
        assert "pipeline inferred from directory name: drg" in out

    def test_the_fallback_warning_prints_once_per_invocation(self, tmp_path, capsys):
        root = str(tmp_path / "results")
        for key in ("baseline", "biomedbert", "bluebert"):
            _make_run(root, key, "05082026_18-55-32")
        compare_models.resolve_pipeline(root, None)
        assert capsys.readouterr().out.count("[WARN] no run_metadata.json") == 1

    def test_the_warning_prints_even_when_pipeline_is_explicit(self, tmp_path, capsys):
        """The absence of provenance is a fact about the tree, not about the flag."""
        root = str(tmp_path / "results_p5")
        _make_run(root, "baseline", "06082026_15-18-52")
        assert compare_models.resolve_pipeline(root, "drg") == "drg"
        out = capsys.readouterr().out
        assert "[WARN] no run_metadata.json under" in out
        assert "pipeline: drg (explicit)" in out

    def test_a_mixed_tree_is_a_hard_error_naming_both_runs(self, tmp_path):
        root = str(tmp_path / "results")
        legacy_run = _make_run(root, "baseline", "05082026_18-55-32", "legacy")
        drg_run = _make_run(root, "biomedbert", "06082026_15-42-04", "drg")

        with pytest.raises(SystemExit) as excinfo:
            compare_models.resolve_pipeline(root, None)
        message = str(excinfo.value)
        assert "mixed-pipeline" in message
        # Both runs named: the reader's next action is to look at them.
        assert legacy_run in message and drg_run in message
        assert "'legacy'" in message and "'drg'" in message

    def test_a_mixed_tree_is_caught_across_two_runs_of_one_arm(self, tmp_path):
        """Every run is inspected, not just the latest per arm.

        The report draws one run per arm, so a stale run from another pipeline
        would otherwise sit in the same root, uninspected and invisible.
        """
        root = str(tmp_path / "results")
        _make_run(root, "baseline", "05082026_18-55-32", "legacy")
        _make_run(root, "baseline", "06082026_15-18-52", "drg")
        with pytest.raises(SystemExit, match="mixed-pipeline"):
            compare_models.resolve_pipeline(root, None)

    def test_partial_migration_in_time_is_not_a_mixed_tree(self, tmp_path, capsys):
        """Old runs beside one fresh run is normal; only mixed PIPELINES are not."""
        root = str(tmp_path / "results_corrected")
        _make_run(root, "baseline", "05082026_18-55-32")  # pre-C8, no metadata
        _make_run(root, "biomedbert", "06082026_15-42-04", "corrected")

        assert compare_models.resolve_pipeline(root, None) == "corrected"
        assert "[WARN] no run_metadata.json" not in capsys.readouterr().out

    def test_malformed_metadata_is_treated_as_absent(self, tmp_path, capsys):
        """A provenance file must not be able to kill a report the numbers support."""
        root = str(tmp_path / "results")
        path = _make_run(root, "baseline", "05082026_18-55-32")
        with open(os.path.join(path, "run_metadata.json"), "w", encoding="utf-8") as f:
            f.write("{not json at all")

        assert compare_models.resolve_pipeline(root, None) == "legacy"
        assert "[WARN] no run_metadata.json" in capsys.readouterr().out

    def test_a_null_pipeline_name_is_treated_as_absent(self, tmp_path, capsys):
        """A hand-built config records ``name: null``; there is nothing to read."""
        root = str(tmp_path / "results")
        _make_run(root, "baseline", "05082026_18-55-32", None)
        path = os.path.join(root, "baseline", "05082026_18-55-32")
        with open(os.path.join(path, "run_metadata.json"), "w", encoding="utf-8") as f:
            json.dump({"metadata_version": 1, "pipeline": {"name": None}}, f)

        assert compare_models.resolve_pipeline(root, None) == "legacy"
        assert "[WARN] no run_metadata.json" in capsys.readouterr().out

    def test_explicit_flag_still_wins_over_metadata_but_says_they_disagree(
        self, tmp_path, capsys
    ):
        root = str(tmp_path / "results")
        _make_run(root, "baseline", "05082026_18-55-32", "drg")
        assert compare_models.resolve_pipeline(root, "legacy") == "legacy"
        out = capsys.readouterr().out
        assert "records pipeline 'drg'" in out
        assert "using the explicit flag" in out

    def test_an_unknown_dirname_with_no_metadata_still_refuses(self, tmp_path, capsys):
        """The pre-existing hard refusal is untouched for metadata-less trees."""
        root = str(tmp_path / "some_scratch_dir")
        _make_run(root, "baseline", "05082026_18-55-32")
        with pytest.raises(SystemExit, match="cannot tell which pipeline"):
            compare_models.resolve_pipeline(root, None)


# ---------------------------------------------------------------------------
# The writers call it, and call it LAST
# ---------------------------------------------------------------------------


class TestCallSites:
    """The one way this commit could break the byte-exact golden.

    Every added line in ``src/aicds/models/`` must sit strictly AFTER the block
    that owns ``PerformanceIndex.txt`` has closed -- the same discipline as
    ``RankAccumulator.write``, and for the same reason: an exception raised
    before the timing trailer is written would surface as
    ``test_golden.strip_trailer``'s "No timing trailer found", i.e. a GOLDEN
    FAILURE THAT LOOKS LIKE THE PIPELINE CHANGED.

    Asserted on the source text because the alternative is a full 10-fold run.
    """

    @pytest.mark.parametrize(
        "module,close_marker",
        [
            ("baseline_sent2vec.py", "performance_out_file.write(line + \"\\n\")"),
            ("bert_models.py", "performance_out_file.close()"),
        ],
    )
    def test_metadata_is_written_after_the_performance_index_closes(
        self, module, close_marker
    ):
        path = os.path.join(
            os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
            "src",
            "aicds",
            "models",
            module,
        )
        with open(path, encoding="utf-8") as handle:
            text = handle.read()

        call = text.index("runs.write_run_metadata(")
        assert text.rindex(close_marker) < call, module
        # And after the rank metrics, so the file's presence means the run
        # reached the very end.
        assert text.rindex("rank_accumulator.write(") < call, module
        # Nothing may touch the performance handle afterwards.
        assert "performance_out_file" not in text[call:], module
